export type Category = "Handbags" | "Timepieces" | "Jewelry" | "Eyewear" | "Footwear";

export type Item = {
  lot: string;
  slug: string;
  name: string;
  maker: string;
  category: Category;
  era: string;
  condition: "Brand New" | "Excellent" | "Very Good";
  price: number;
  estRetail: number;
  likes: number;
  image: string;
  aspect: number; // width / height, drives the masonry rhythm
  description: string;
  provenance: string;
};

export const items: Item[] = [
  {
    lot: "0114",
    slug: "slouch-hobo-noir",
    name: "Slouch Hobo, Noir",
    maker: "Maison Vevette",
    category: "Handbags",
    era: "Late 1990s",
    condition: "Excellent",
    price: 2850,
    estRetail: 3475,
    likes: 6,
    image: "https://images.unsplash.com/photo-1758542988969-39a10168b2ce?q=80&w=1200&auto=format&fit=crop",
    aspect: 0.75,
    description:
      "Unstructured black leather, soft enough to fold flat, holds its slouch by weight alone. No hardware to date it — this shape never really left.",
    provenance: "Acquired from an estate collection, Zurich. Full authentication report on file.",
  },
  {
    lot: "0219",
    slug: "skeleton-automatic-steel",
    name: "Skeleton Automatic, Steel",
    maker: "Rousset & Fils",
    category: "Timepieces",
    era: "1988",
    condition: "Very Good",
    price: 7400,
    estRetail: 9490,
    likes: 4,
    image: "https://images.unsplash.com/photo-1729078946289-92397e8d0b58?q=80&w=1200&auto=format&fit=crop",
    aspect: 1.5,
    description:
      "Open-worked dial, movement visible under the crystal. Serviced eleven months ago; runs within four seconds a day.",
    provenance: "Consigned by a private collector in Geneva. Original papers included.",
  },
  {
    lot: "0087",
    slug: "dress-watch-gold-bracelet",
    name: "Dress Watch, Gold Bracelet",
    maker: "Hallworth",
    category: "Timepieces",
    era: "1970s",
    condition: "Excellent",
    price: 5400,
    estRetail: 6350,
    likes: 24,
    image: "https://images.unsplash.com/photo-1541778480-fc1752bbc2a9?q=80&w=1200&auto=format&fit=crop",
    aspect: 1.72,
    description:
      "18k gold case and integrated bracelet, hand-wound. The kind of quiet piece that reads louder than it looks.",
    provenance: "Sourced through a specialist dealer in London.",
  },
  {
    lot: "0302",
    slug: "woven-tote-cognac",
    name: "Woven Tote, Cognac",
    maker: "Adler & Boon",
    category: "Handbags",
    era: "Early 2010s",
    condition: "Brand New",
    price: 2650,
    estRetail: 3010,
    likes: 11,
    image: "https://images.unsplash.com/photo-1598532163257-ae3c6b2524b6?q=80&w=1200&auto=format&fit=crop",
    aspect: 0.8,
    description:
      "Hand-woven intrecciato leather in a cognac that only deepens with age. Interior is unmarked; weave shows no wear.",
    provenance: "Single owner, smoke-free home. Dust bag and authentication card included.",
  },
  {
    lot: "0455",
    slug: "crocodile-embossed-bag-rouge",
    name: "Crocodile-Embossed Bag, Rouge",
    maker: "Maison Vevette",
    category: "Handbags",
    era: "2016",
    condition: "Excellent",
    price: 3100,
    estRetail: 3875,
    likes: 18,
    image: "https://images.unsplash.com/photo-1575032617751-6ddec2089882?q=80&w=1200&auto=format&fit=crop",
    aspect: 0.8,
    description:
      "Embossed leather in a rouge that has not faded, brass turn-lock closure. Carried soft, kept careful.",
    provenance: "Purchased new, worn twice, consigned by the original buyer.",
  },
  {
    lot: "0176",
    slug: "leather-derby-oxblood",
    name: "Leather Derby, Oxblood",
    maker: "Corwin Bootmakers",
    category: "Footwear",
    era: "2019",
    condition: "Very Good",
    price: 480,
    estRetail: 533,
    likes: 3,
    image: "https://images.unsplash.com/photo-1641893843833-a006778dc00b?q=80&w=1200&auto=format&fit=crop",
    aspect: 1.46,
    description:
      "Goodyear-welted, resoled once by the maker. Broken in, not broken down — the leather has the give of a shoe that fit its first owner well.",
    provenance: "Consigned directly by original owner with receipt.",
  },
  {
    lot: "0398",
    slug: "weekend-satchel-espresso",
    name: "Weekend Satchel, Espresso",
    maker: "Adler & Boon",
    category: "Handbags",
    era: "2015",
    condition: "Very Good",
    price: 1890,
    estRetail: 2198,
    likes: 9,
    image: "https://images.unsplash.com/photo-1473188588951-666fce8e7c68?q=80&w=1200&auto=format&fit=crop",
    aspect: 1.68,
    description:
      "Saddle leather with buckles gone soft at the edges. Honest wear on the base, nothing structural.",
    provenance: "Estate consignment, documented chain of ownership.",
  },
  {
    lot: "0061",
    slug: "field-chronograph-two-tone",
    name: "Field Chronograph, Two-Tone",
    maker: "Rousset & Fils",
    category: "Timepieces",
    era: "1995",
    condition: "Excellent",
    price: 6700,
    estRetail: 8272,
    likes: 15,
    image: "https://images.unsplash.com/photo-1623998021661-dc7555b2213d?q=80&w=1200&auto=format&fit=crop",
    aspect: 1.51,
    description:
      "Steel and rose gold, navy sunburst dial, automatic movement. Bracelet has been sized once by a professional.",
    provenance: "Purchased from Rousset & Fils boutique, original owner traceable.",
  },
  {
    lot: "0510",
    slug: "diamond-solitaire-pave-band",
    name: "Diamond Solitaire, Pavé Band",
    maker: "Solenne",
    category: "Jewelry",
    era: "2000s",
    condition: "Brand New",
    price: 6950,
    estRetail: 7554,
    likes: 27,
    image: "https://images.unsplash.com/photo-1598560917807-1bae44bd2be8?q=80&w=1200&auto=format&fit=crop",
    aspect: 1.0,
    description:
      "Emerald-cut center stone, pavé shoulders, hallmarked. Recently cleaned and inspected by our jeweler — every stone accounted for.",
    provenance: "Private consignment, gemological report available on request.",
  },
  {
    lot: "0443",
    slug: "drop-earrings-champagne-pave",
    name: "Drop Earrings, Champagne Pavé",
    maker: "Solenne",
    category: "Jewelry",
    era: "1960s",
    condition: "Excellent",
    price: 2200,
    estRetail: 2619,
    likes: 7,
    image: "https://images.unsplash.com/photo-1705326454933-9685fc6888e1?q=80&w=1200&auto=format&fit=crop",
    aspect: 0.67,
    description:
      "Champagne pavé drops in yellow gold settings, original clip backs converted to posts by a jeweler on request.",
    provenance: "Sourced from a family estate, three generations of ownership documented.",
  },
  {
    lot: "0027",
    slug: "aviator-tortoise-acetate",
    name: "Aviator, Tortoise Acetate",
    maker: "Lindqvist Opticians",
    category: "Eyewear",
    era: "2018",
    condition: "Very Good",
    price: 310,
    estRetail: 397,
    likes: 5,
    image: "https://images.unsplash.com/photo-1759227922040-0ca4d3cbe42e?q=80&w=1200&auto=format&fit=crop",
    aspect: 0.75,
    description:
      "Hand-polished tortoise acetate, minor wear at the temple tips. Lenses replaced with fresh glass.",
    provenance: "Consigned with original case.",
  },
  {
    lot: "0289",
    slug: "round-sun-gold-wire",
    name: "Round Sun, Gold Wire",
    maker: "Lindqvist Opticians",
    category: "Eyewear",
    era: "1970s",
    condition: "Excellent",
    price: 265,
    estRetail: 319,
    likes: 2,
    image: "https://images.unsplash.com/photo-1590564310418-66304f55a2c2?q=80&w=1200&auto=format&fit=crop",
    aspect: 1.5,
    description:
      "Thin gold wire frame, a shape that has never really gone out of circulation.",
    provenance: "Purchased from a specialist vintage optician in Paris.",
  },
  {
    lot: "0333",
    slug: "ankle-strap-heel-noir",
    name: "Ankle-Strap Heel, Noir",
    maker: "Corwin Bootmakers",
    category: "Footwear",
    era: "2020",
    condition: "Brand New",
    price: 540,
    estRetail: 593,
    likes: 8,
    image: "https://images.unsplash.com/photo-1659261448687-6d01466e06e4?q=80&w=1200&auto=format&fit=crop",
    aspect: 1.5,
    description:
      "Suede, worn once for an evening. Soles show only the faintest mark of the floor they touched.",
    provenance: "Original owner, box and dust bag included.",
  },
  {
    lot: "0018",
    slug: "pearl-beaded-clutch",
    name: "Pearl-Beaded Clutch",
    maker: "Maison Vevette",
    category: "Handbags",
    era: "1980s",
    condition: "Very Good",
    price: 1650,
    estRetail: 2089,
    likes: 13,
    image: "https://images.unsplash.com/photo-1722510825571-8cdd1fe98ba4?q=80&w=1200&auto=format&fit=crop",
    aspect: 0.75,
    description:
      "Hand-strung pearl beading over a soft frame, clasp still snaps true. A piece built for a single evening at a time.",
    provenance: "Estate sale, Milan. Restored clasp by our in-house atelier.",
  },
  {
    lot: "0472",
    slug: "dive-watch-black-bezel",
    name: "Dive Watch, Black Bezel",
    maker: "Hallworth",
    category: "Timepieces",
    era: "2005",
    condition: "Excellent",
    price: 3800,
    estRetail: 4368,
    likes: 19,
    image: "https://images.unsplash.com/photo-1774299398828-8dc74e92e53c?q=80&w=1200&auto=format&fit=crop",
    aspect: 1.5,
    description:
      "Ceramic bezel, automatic movement, pressure-tested to spec by our watchmaker before listing.",
    provenance: "Consigned by a private collector with full service history.",
  },
  {
    lot: "0501",
    slug: "signet-ring-carved",
    name: "Signet Ring, Hand-Carved",
    maker: "Solenne",
    category: "Jewelry",
    era: "1950s",
    condition: "Excellent",
    price: 1450,
    estRetail: 1629,
    likes: 10,
    image: "https://images.unsplash.com/photo-1705326455036-0fab8ecba04d?q=80&w=1200&auto=format&fit=crop",
    aspect: 1.5,
    description:
      "Solid gold, hand-engraved crest, sized once. The kind of wear that only comes from being worn daily for decades.",
    provenance: "Family estate, provenance letter included.",
  },
];

export function getItemBySlug(slug: string): Item | undefined {
  return items.find((item) => item.slug === slug);
}
